"""
PDF Generation service — government-style legal document PDFs.

Produces formal, structured PDFs that follow Indian government document
formatting conventions: official headers, reference numbers, section dividers,
and stamp/seal placeholders.
"""

import io
import logging
from datetime import datetime, timezone
from typing import Any

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm, mm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable,
    Frame,
    PageTemplate,
)
from reportlab.lib.colors import HexColor, black, white

logger = logging.getLogger("crimegpt.pdf")

# Government-style color palette
_NAVY = HexColor("#1a237e")
_DARK = HexColor("#212121")
_GRAY = HexColor("#616161")
_LIGHT_GRAY = HexColor("#e0e0e0")
_BORDER = HexColor("#bdbdbd")
_RED_ACCENT = HexColor("#b71c1c")


def _header_footer(canvas, doc):
    """Draw government-style header and footer on every page."""
    width, height = A4
    canvas.saveState()

    # ─── TOP BORDER LINE ───
    canvas.setStrokeColor(_NAVY)
    canvas.setLineWidth(2)
    canvas.line(2 * cm, height - 1.5 * cm, width - 2 * cm, height - 1.5 * cm)
    canvas.setLineWidth(0.5)
    canvas.line(2 * cm, height - 1.6 * cm, width - 2 * cm, height - 1.6 * cm)

    # ─── HEADER TEXT ───
    canvas.setFont("Helvetica-Bold", 9)
    canvas.setFillColor(_NAVY)
    canvas.drawCentredString(width / 2, height - 1.3 * cm, "GOVERNMENT OF INDIA — POLICE DEPARTMENT")

    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(_GRAY)
    canvas.drawCentredString(width / 2, height - 1.85 * cm, "Generated by CrimeGPT — AI-Powered Crime Documentation System")

    # ─── BOTTOM BORDER ───
    canvas.setStrokeColor(_NAVY)
    canvas.setLineWidth(2)
    canvas.line(2 * cm, 1.5 * cm, width - 2 * cm, 1.5 * cm)
    canvas.setLineWidth(0.5)
    canvas.line(2 * cm, 1.6 * cm, width - 2 * cm, 1.6 * cm)

    # ─── FOOTER ───
    canvas.setFont("Helvetica", 6.5)
    canvas.setFillColor(_GRAY)
    canvas.drawString(2 * cm, 1.1 * cm, "CONFIDENTIAL — FOR OFFICIAL USE ONLY")
    canvas.drawRightString(width - 2 * cm, 1.1 * cm, f"Page {doc.page}")
    canvas.drawCentredString(
        width / 2, 0.7 * cm,
        f"Document generated on {datetime.now(timezone.utc).strftime('%d/%m/%Y at %H:%M UTC')} — Verify before official use"
    )

    canvas.restoreState()


class PDFService:
    """Generates government-style PDF documents."""

    def generate_pdf(
        self,
        *,
        title: str,
        content: str,
        document_type: str = "",
        fir_number: str | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> bytes:
        """Generate a government-style PDF. Returns raw PDF bytes."""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            topMargin=2.5 * cm,
            bottomMargin=2.5 * cm,
            leftMargin=2.5 * cm,
            rightMargin=2.5 * cm,
        )

        styles = getSampleStyleSheet()
        elements = []

        # ─── Custom Styles (Government form aesthetic) ───

        title_style = ParagraphStyle(
            "GovTitle",
            parent=styles["Title"],
            fontSize=14,
            spaceAfter=4,
            spaceBefore=10,
            textColor=_NAVY,
            alignment=TA_CENTER,
            fontName="Helvetica-Bold",
            leading=18,
        )
        ref_style = ParagraphStyle(
            "GovRef",
            parent=styles["Normal"],
            fontSize=9,
            spaceAfter=2,
            textColor=_DARK,
            alignment=TA_CENTER,
            fontName="Helvetica",
        )
        section_head = ParagraphStyle(
            "SectionHead",
            parent=styles["Heading3"],
            fontSize=10,
            spaceBefore=14,
            spaceAfter=6,
            textColor=_NAVY,
            fontName="Helvetica-Bold",
            borderPadding=(0, 0, 2, 0),
        )
        body_style = ParagraphStyle(
            "GovBody",
            parent=styles["Normal"],
            fontSize=9.5,
            leading=14,
            spaceAfter=6,
            textColor=_DARK,
            alignment=TA_JUSTIFY,
            fontName="Helvetica",
        )
        field_label = ParagraphStyle(
            "FieldLabel",
            parent=styles["Normal"],
            fontSize=8,
            textColor=_GRAY,
            fontName="Helvetica-Bold",
        )
        stamp_style = ParagraphStyle(
            "StampBlock",
            parent=styles["Normal"],
            fontSize=8,
            textColor=_GRAY,
            alignment=TA_RIGHT,
            fontName="Helvetica-Oblique",
        )

        # ═══════ DOCUMENT HEADER ═══════

        # Emblem placeholder
        elements.append(Spacer(1, 4 * mm))
        elements.append(Paragraph("⚖", ParagraphStyle(
            "Emblem", parent=styles["Normal"], fontSize=28,
            alignment=TA_CENTER, textColor=_NAVY,
        )))
        elements.append(Spacer(1, 2 * mm))

        # Title
        elements.append(Paragraph(title.upper(), title_style))

        # Reference line
        ref_parts = []
        if fir_number:
            ref_parts.append(f"FIR No.: {fir_number}")
        ref_parts.append(f"Date: {datetime.now(timezone.utc).strftime('%d/%m/%Y')}")
        ref_parts.append(f"Ref: CG/{document_type.upper()[:4]}/{datetime.now().strftime('%Y%m%d%H%M')}")
        elements.append(Paragraph(" | ".join(ref_parts), ref_style))

        elements.append(Spacer(1, 3 * mm))

        # Double rule
        elements.append(HRFlowable(width="100%", thickness=1.5, color=_NAVY))
        elements.append(Spacer(1, 1 * mm))
        elements.append(HRFlowable(width="100%", thickness=0.5, color=_NAVY))
        elements.append(Spacer(1, 6 * mm))

        # ═══════ METADATA TABLE (if available) ═══════

        meta = metadata or {}
        complainant = meta.get("complainant", {})
        accused = meta.get("accused", {})

        if complainant.get("name") or meta.get("officer_badge"):
            meta_rows = []
            if complainant.get("name"):
                meta_rows.append(["Complainant:", complainant.get("name", "—")])
            if complainant.get("address"):
                meta_rows.append(["Address:", complainant.get("address", "—")])
            if accused.get("name"):
                meta_rows.append(["Accused:", accused.get("name", "—")])
            if meta.get("location"):
                meta_rows.append(["Location:", meta.get("location", "—")])
            if meta.get("officer_badge"):
                meta_rows.append(["IO Badge:", meta.get("officer_badge", "—")])

            if meta_rows:
                t = Table(meta_rows, colWidths=[3.5 * cm, 12 * cm])
                t.setStyle(TableStyle([
                    ("FONT", (0, 0), (0, -1), "Helvetica-Bold", 8),
                    ("FONT", (1, 0), (1, -1), "Helvetica", 9),
                    ("TEXTCOLOR", (0, 0), (0, -1), _GRAY),
                    ("TEXTCOLOR", (1, 0), (1, -1), _DARK),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                    ("TOPPADDING", (0, 0), (-1, -1), 2),
                    ("LINEBELOW", (0, 0), (-1, -2), 0.3, _LIGHT_GRAY),
                ]))
                elements.append(t)
                elements.append(Spacer(1, 6 * mm))
                elements.append(HRFlowable(width="100%", thickness=0.5, color=_BORDER))
                elements.append(Spacer(1, 4 * mm))

        # ═══════ DOCUMENT BODY ═══════

        for line in content.split("\n"):
            line = line.strip()
            if not line:
                elements.append(Spacer(1, 3 * mm))
                continue

            # Section headers (--- Title ---)
            if line.startswith("---") and line.endswith("---"):
                section_title = line.strip("-").strip()
                elements.append(Spacer(1, 2 * mm))
                elements.append(HRFlowable(width="30%", thickness=0.5, color=_NAVY))
                elements.append(Paragraph(section_title.upper(), section_head))
                continue

            # Divider lines (===)
            if line.startswith("=") and len(line) > 5:
                elements.append(HRFlowable(width="100%", thickness=1, color=_NAVY))
                continue

            # Numbered items
            if line and line[0].isdigit() and "." in line[:4]:
                elements.append(Paragraph(
                    line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"),
                    ParagraphStyle("NumberedItem", parent=body_style, leftIndent=10),
                ))
                continue

            # Regular body text
            safe_line = (
                line.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
            )
            elements.append(Paragraph(safe_line, body_style))

        # ═══════ SIGNATURE BLOCK ═══════

        elements.append(Spacer(1, 15 * mm))
        elements.append(HRFlowable(width="100%", thickness=0.5, color=_BORDER))
        elements.append(Spacer(1, 8 * mm))

        sig_data = [
            ["", ""],
            ["Signature: ____________________", "Signature: ____________________"],
            ["Investigating Officer", "Station House Officer"],
            [f"Badge: {meta.get('officer_badge', '[___]')}", "Badge: [___]"],
            ["Date: [___]", "Date: [___]"],
        ]
        sig_table = Table(sig_data, colWidths=[7.5 * cm, 7.5 * cm])
        sig_table.setStyle(TableStyle([
            ("FONT", (0, 0), (-1, -1), "Helvetica", 8),
            ("FONT", (0, 2), (-1, 2), "Helvetica-Bold", 8),
            ("TEXTCOLOR", (0, 0), (-1, -1), _DARK),
            ("ALIGN", (0, 0), (0, -1), "LEFT"),
            ("ALIGN", (1, 0), (1, -1), "RIGHT"),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ]))
        elements.append(sig_table)

        # Stamp placeholder
        elements.append(Spacer(1, 10 * mm))
        elements.append(Paragraph("[OFFICIAL SEAL / STAMP]", stamp_style))

        # ═══════ BUILD PDF ═══════

        doc.build(elements, onFirstPage=_header_footer, onLaterPages=_header_footer)
        pdf_bytes = buffer.getvalue()
        buffer.close()

        logger.info(f"PDF generated: {title} ({len(pdf_bytes)} bytes)")
        return pdf_bytes
